export const skills = [
    "HTML",
    "CSS",
    "CSS - FLEX, GRID, StyledComponents",
    "Responsing web Design",
    "JavaScript: ES6+",
    "Immutability",
    "React",
    "React Hooks",
    "Redux (Toolkit)",
    "Redux-Saga",
    "React Router",
    "Promises, Async/Await",
    "Working with API (fetch, axios",
    "Error handling",
    "Markdown",
    "Debugging",
    "Git",
    "GitHub Pull Request & Review",
    "NPM",
    "Scrum",
    "Teamwork",
    "Trello",
];

export const nextSkills = [
    "Node.js",
    "TypeScript",
    "Js classes",
    "React Context",
];